spring:
  application:
    name: servicio-hoteles
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/viajes?serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server: 
  port: 8000
# Config de el servidor  
eureka:
  client:
    serviceUrl:
      # Direccion a la que se conecta el microservicio con eureka
      defaultZone: http://localhost:8761/eureka

#si VPN comentado, no VPN descomentado (en ambos casos reiniciar gateway y micros)
#eureka.instance.preferIpAddress: true
  #instance:
    #preferIpAddress: true